/**
 * Project portfolio data, generated from `Project Portfolio/` (PROJECTS LIST.pdf
 * and the UG Project Portfolio Logos folders). Logo display names are derived
 * from the source filenames and lightly cleaned; refine against the client's
 * preferred spelling as needed. Logos live in public/images/projects/<sector>/.
 */

export interface ProjectLogo {
  name: string;
  logo: string;
}

export interface ProjectSector {
  slug: string;
  name: string;
  logos: ProjectLogo[];
}

export interface ProjectRegion {
  name: string;
  projects: string[];
}


export const projectCount = 223;

export const exportMarkets = ["UAE", "Oman", "Nepal", "Sri Lanka"];

export const sectors: ProjectSector[] = [
  {
    slug: "government-institutions",
    name: "Government Institutions",
    logos: [
      { name: "Bus Rapid Transit", logo: "/images/projects/government-institutions/bus-rapid-transit.jpg" },
      { name: "DCO Office Faisalabad", logo: "/images/projects/government-institutions/dco-office-faisalabad.jpg" },
      { name: "FBR", logo: "/images/projects/government-institutions/fbr.jpg" },
      { name: "Islamabad High Court", logo: "/images/projects/government-institutions/islamabad-high-court.png" },
      { name: "Lahore High Court", logo: "/images/projects/government-institutions/lahore-high-court.jpg" },
      { name: "National Development Complex", logo: "/images/projects/government-institutions/national-development-complex.webp" },
      { name: "National Logistics Cell", logo: "/images/projects/government-institutions/national-logistics-cell.jpg" },
      { name: "Pakistan Air Force", logo: "/images/projects/government-institutions/pakistan-air-force.png" },
      { name: "Pepda Lahore", logo: "/images/projects/government-institutions/pepda-lahore.jpg" },
      { name: "Peshawar Karachi Motorway", logo: "/images/projects/government-institutions/peshawar-karachi-motorway.jpg" },
      { name: "PHA Foundation Ministry of Housing & Works", logo: "/images/projects/government-institutions/pha-foundation-ministry-of-housing-works.png" },
      { name: "Punjab Power Plant", logo: "/images/projects/government-institutions/punjab-power-plant.jpg" },
      { name: "Thar Coal Field", logo: "/images/projects/government-institutions/thar-coal-field.jpg" },
    ],
  },
  {
    slug: "building-and-housing",
    name: "Building & Housing",
    logos: [
      { name: "Ali Villa", logo: "/images/projects/building-and-housing/ali-villa.jpg" },
      { name: "Askari Tower", logo: "/images/projects/building-and-housing/askari-tower.jpg" },
      { name: "Bahria Heights", logo: "/images/projects/building-and-housing/bahria-heights.jpg" },
      { name: "Bahria Town Head Office", logo: "/images/projects/building-and-housing/bahria-town-head-office.jpg" },
      { name: "Basha Dam", logo: "/images/projects/building-and-housing/basha-dam.jpg" },
      { name: "Bioron Medics", logo: "/images/projects/building-and-housing/bioron-medics.jpg" },
      { name: "Brentwood Signature", logo: "/images/projects/building-and-housing/brentwood-signature.jpg" },
      { name: "City Towers & Shopping Mall", logo: "/images/projects/building-and-housing/city-towers-shopping-mall.jpg" },
      { name: "Dasu Dam", logo: "/images/projects/building-and-housing/dasu-dam.jpg" },
      { name: "DCI Tower Islamabad", logo: "/images/projects/building-and-housing/dci-tower-islamabad.png" },
      { name: "DHA Multan", logo: "/images/projects/building-and-housing/dha-multan.jpg" },
      { name: "Diamond Residency", logo: "/images/projects/building-and-housing/diamond-residency.png" },
      { name: "Eighteen Islamabad", logo: "/images/projects/building-and-housing/eighteen-islamabad.jpg" },
      { name: "Emaar Crescent", logo: "/images/projects/building-and-housing/emaar-crescent.png" },
      { name: "Hoshang Pearl", logo: "/images/projects/building-and-housing/hoshang-pearl.jpg" },
      { name: "One Constitution Avinue", logo: "/images/projects/building-and-housing/one-constitution-avinue.png" },
      { name: "Paragon Towers", logo: "/images/projects/building-and-housing/paragon-towers.jpg" },
      { name: "Sawera Club", logo: "/images/projects/building-and-housing/sawera-club.jpg" },
      { name: "Serene Heights Gulberg", logo: "/images/projects/building-and-housing/serene-heights-gulberg.png" },
      { name: "Sukh Chayn Residence", logo: "/images/projects/building-and-housing/sukh-chayn-residence.jpg" },
      { name: "Terrace Apartment Park", logo: "/images/projects/building-and-housing/terrace-apartment-park.jpg" },
      { name: "The Court Heights", logo: "/images/projects/building-and-housing/the-court-heights.jpg" },
      { name: "Zarkon Height Tower", logo: "/images/projects/building-and-housing/zarkon-height-tower.jpg" },
    ],
  },
  {
    slug: "shopping-malls",
    name: "Shopping Malls",
    logos: [
      { name: "Amana Mall", logo: "/images/projects/shopping-malls/amana-mall.jpg" },
      { name: "City Cash & Carry", logo: "/images/projects/shopping-malls/city-cash-carry.jpg" },
      { name: "Diamond Mall & Residency", logo: "/images/projects/shopping-malls/diamond-mall-residency.jpg" },
      { name: "Downtown Mall", logo: "/images/projects/shopping-malls/downtown-mall.png" },
      { name: "Family Mart", logo: "/images/projects/shopping-malls/family-mart.jpg" },
      { name: "Giga Mall", logo: "/images/projects/shopping-malls/giga-mall.jpg" },
      { name: "Gulberg Heights", logo: "/images/projects/shopping-malls/gulberg-heights.jpg" },
      { name: "Gulberg Pride", logo: "/images/projects/shopping-malls/gulberg-pride.jpg" },
      { name: "Hangten Lahore", logo: "/images/projects/shopping-malls/hangten-lahore.jpg" },
      { name: "Imtiaz Mega Zamzama", logo: "/images/projects/shopping-malls/imtiaz-mega-zamzama.png" },
      { name: "Imtiyaz Store Behria Town", logo: "/images/projects/shopping-malls/imtiyaz-store-behria-town.png" },
      { name: "Indigo Height", logo: "/images/projects/shopping-malls/indigo-height.jpg" },
      { name: "J. Branches Faisalabad", logo: "/images/projects/shopping-malls/j-branches-faisalabad.png" },
      { name: "Kayseria Lahore", logo: "/images/projects/shopping-malls/kayseria-lahore.jpg" },
      { name: "Lake City Mall", logo: "/images/projects/shopping-malls/lake-city-mall.jpg" },
      { name: "Lucky One Mall", logo: "/images/projects/shopping-malls/lucky-one-mall.jpg" },
      { name: "Lyallpur Galleria", logo: "/images/projects/shopping-malls/lyallpur-galleria.jpg" },
      { name: "Ndure Outlet", logo: "/images/projects/shopping-malls/ndure-outlet.png" },
      { name: "Packages Mall", logo: "/images/projects/shopping-malls/packages-mall.jpg" },
      { name: "Pak China Mall", logo: "/images/projects/shopping-malls/pak-china-mall.jpg" },
      { name: "Premier Choice", logo: "/images/projects/shopping-malls/premier-choice.jpg" },
      { name: "Skypark One", logo: "/images/projects/shopping-malls/skypark-one.jpg" },
      { name: "Square One Mall", logo: "/images/projects/shopping-malls/square-one-mall.jpg" },
      { name: "Stylo Shoes", logo: "/images/projects/shopping-malls/stylo-shoes.jpg" },
      { name: "The Royal Mall", logo: "/images/projects/shopping-malls/the-royal-mall.jpg" },
      { name: "Xinwa Mall", logo: "/images/projects/shopping-malls/xinwa-mall.jpg" },
    ],
  },
  {
    slug: "hospitals",
    name: "Hospitals & Care",
    logos: [
      { name: "Alkhidmat Hospital", logo: "/images/projects/hospitals/alkhidmat-hospital.png" },
      { name: "Allied Hospital", logo: "/images/projects/hospitals/allied-hospital.jpg" },
      { name: "Bacha Khan Medical Complex", logo: "/images/projects/hospitals/bacha-khan-medical-complex.jpg" },
      { name: "Care Hospital Lahore", logo: "/images/projects/hospitals/care-hospital-lahore.jpg" },
      { name: "Civil Hospital Faisalabad", logo: "/images/projects/hospitals/civil-hospital-faisalabad.jpg" },
      { name: "Civil Hospital Karachi", logo: "/images/projects/hospitals/civil-hospital-karachi.jpg" },
      { name: "Civil Hospital Lahore", logo: "/images/projects/hospitals/civil-hospital-lahore.jpg" },
      { name: "CMH Lahore Medical College", logo: "/images/projects/hospitals/cmh-lahore-medical-college.jpg" },
      { name: "DHQ Hopsital Swabi", logo: "/images/projects/hospitals/dhq-hopsital-swabi.jpg" },
      { name: "Dr. Ziauddin Hospital", logo: "/images/projects/hospitals/dr-ziauddin-hospital.jpg" },
      { name: "Government General Hospital", logo: "/images/projects/hospitals/government-general-hospital.jpg" },
      { name: "Hospital Ahmedpur Sharqia", logo: "/images/projects/hospitals/hospital-ahmedpur-sharqia.jpg" },
      { name: "Indus Hospital Lahore", logo: "/images/projects/hospitals/indus-hospital-lahore.jpg" },
      { name: "K.P.K Rescue Service 1122", logo: "/images/projects/hospitals/k-p-k-rescue-service-1122.jpg" },
      { name: "Karachi Institute of Kidney", logo: "/images/projects/hospitals/karachi-institute-of-kidney.jpg" },
      { name: "KRL Hospital", logo: "/images/projects/hospitals/krl-hospital.jpg" },
      { name: "Lahore Medical & Dental College", logo: "/images/projects/hospitals/lahore-medical-dental-college.jpg" },
      { name: "Mother & Child Hospital Layyah", logo: "/images/projects/hospitals/mother-child-hospital-layyah.jpg" },
      { name: "Mother & Child Hospital Mianwali", logo: "/images/projects/hospitals/mother-child-hospital-mianwali.jpg" },
      { name: "MYO Hoapital Lahore", logo: "/images/projects/hospitals/myo-hoapital-lahore.jpg" },
      { name: "Omar Hospital Lahore", logo: "/images/projects/hospitals/omar-hospital-lahore.jpg" },
      { name: "PAF Hospital", logo: "/images/projects/hospitals/paf-hospital.png" },
      { name: "PINUM Cancer Hospital", logo: "/images/projects/hospitals/pinum-cancer-hospital.png" },
    ],
  },
  {
    slug: "hospitality",
    name: "Hospitality",
    logos: [
      { name: "Mall of Islamabad", logo: "/images/projects/hospitality/mall-of-islamabad.jpg" },
      { name: "Movenpick Hotel", logo: "/images/projects/hospitality/movenpick-hotel.png" },
      { name: "Ramada Hotel Murree", logo: "/images/projects/hospitality/ramada-hotel-murree.jpg" },
    ],
  },
  {
    slug: "education",
    name: "Education",
    logos: [
      { name: "Aspire College", logo: "/images/projects/education/aspire-college.jpg" },
      { name: "Beaconhouse School Lahore", logo: "/images/projects/education/beaconhouse-school-lahore.jpg" },
      { name: "Beaconhouse School Multan", logo: "/images/projects/education/beaconhouse-school-multan.jpg" },
      { name: "Government College University", logo: "/images/projects/education/government-college-university.jpg" },
      { name: "Jinnah Poly Technic Institute", logo: "/images/projects/education/jinnah-poly-technic-institute.jpg" },
      { name: "Kashmir Pre-engineered Construction", logo: "/images/projects/education/kashmir-pre-engineered-construction.jpg" },
      { name: "King Edward Medical University", logo: "/images/projects/education/king-edward-medical-university.jpg" },
      { name: "MAP Hostel Lahore", logo: "/images/projects/education/map-hostel-lahore.jpg" },
      { name: "Mohammad Ali Jinnah University", logo: "/images/projects/education/mohammad-ali-jinnah-university.jpg" },
      { name: "Punjab Group of Collegs", logo: "/images/projects/education/punjab-group-of-collegs.png" },
      { name: "Ripha University Lahore", logo: "/images/projects/education/ripha-university-lahore.jpg" },
      { name: "University of Central Punjab", logo: "/images/projects/education/university-of-central-punjab.png" },
      { name: "University of Lahore", logo: "/images/projects/education/university-of-lahore.png" },
    ],
  },
  {
    slug: "other-clients",
    name: "Other Clients",
    logos: [
      { name: "Arts Concil Larkana Sindh", logo: "/images/projects/other-clients/arts-concil-larkana-sindh.jpg" },
      { name: "DHA Bahawalpur", logo: "/images/projects/other-clients/dha-bahawalpur.jpg" },
      { name: "Duniya News", logo: "/images/projects/other-clients/duniya-news.jpg" },
      { name: "OPTP Resturant", logo: "/images/projects/other-clients/optp-resturant.jpg" },
      { name: "Paradise Marquee", logo: "/images/projects/other-clients/paradise-marquee.jpg" },
      { name: "Proton Canal Road", logo: "/images/projects/other-clients/proton-canal-road.jpg" },
      { name: "Victoria Marquee", logo: "/images/projects/other-clients/victoria-marquee.jpg" },
    ],
  },
  {
    slug: "banks",
    name: "Banks",
    logos: [
      { name: "Allied-bank", logo: "/images/projects/banks/allied-bank.webp" },
      { name: "Bank of Punjab", logo: "/images/projects/banks/bank-of-punjab.jpg" },
      { name: "HBL Bank", logo: "/images/projects/banks/hbl-bank.jpg" },
      { name: "Meezan Bank", logo: "/images/projects/banks/meezan-bank.jpg" },
      { name: "U Bank", logo: "/images/projects/banks/u-bank.jpg" },
      { name: "UBL Bank", logo: "/images/projects/banks/ubl-bank.png" },
    ],
  },
];

export const regions: ProjectRegion[] = [
  {
    name: "National",
    projects: [
      "National Development Complex (NDC) Various Projects",
      "Peshawar Karachi Motorway (PKM) Sukkur Multan Section",
      "Pearl Continental Hotel, District Mir Pur AJK",
      "Ramada Hotel Murree",
      "Dasu Dam Buildings",
      "Diamer Basha Dam Buildings",
      "Bus Rapid Transit (peshawar Brt)",
      "Khaadi Peshawar",
      "PEC Regional Office Building Peshawar",
      "Hospital Ahmedpur Sharqia",
      "THQ Hospital Arifwala Government of Punjab",
      "Establishment of Emergency K.P.K Rescue Service (rescue 1122) in Distt Swabi",
      "Re-construction of Old DHQ Hopsital Swabi (phase-1)",
      "Bacha Khan Medical Complex Swabi",
      "Mother & Child Hospital Nursing College District Mianwali Government of Punjab",
      "Arts Concil Larkana Sindh",
      "Mother & Child Hospital Nursing College District Layyah Government of Punjab",
      "Nawaz Shareef Cardiology Hospital Sargodha Government of Punjab",
      "Thar Coal Field Islamkot Sindh",
      "OPTP Resturant Quetta",
      "Alkhidmat Hospital Multan",
      "Mother & Child Hospital Multan Government of Punjab",
      "Beaconhouse Schools Multan",
      "CIMS Dental College Multan",
      "Civil Secretarial Multan",
      "DHA Multan Head Office",
      "Nishtar Hospital Multan",
      "Children's Hospital & the Institute of Child Health Multan",
      "High Court Multan Bench Multan",
      "Banquet Hall DHA Bahawalpur",
      "Innovista Cholistan DHA Bahawalpur",
      "Punjab Power Plant Jhang",
      "Innovista Technology Zone DHA Gujranwala",
      "Falett,s Grand Hotel Galyaat, Ayubia",
      "Export in Sri Lanka Various Projects by Authorized Distributor",
      "Export in UAE Various Projects by Authorized Distributor",
      "Export in Nepal Various Projects by Authorized Distributor",
      "Expot in Oman Various Projects by Authorized Distributor",
      "Meezan Bank Branches",
      "U Bank Branches",
      "HBL Microfinance Bank Branches",
      "United Bank Limited",
    ],
  },
  {
    name: "Islamabad and Rawalpindi",
    projects: [
      "Eighteen Islamabad",
      "Giga Mall Islamabad",
      "D Mall Giga Islamabad",
      "Movenpick Hotel Centaurus Islamabad",
      "(NLC) National Logistics Cell Head Quarter Rawalpindi",
      "Gulberg Pride, Gulberg Residencia Islamabad",
      "The Royal Mall and Residency Islamabad",
      "PHA Foundation Ministry of Housing & Works Government of Pakistan Prime Minister's Housing Program",
      "DCI Towers Defence Complex Islamabad",
      "Mall of Islamabad, Islamabad",
      "The Islamabad High Court, Islamabad",
      "Zarkon Height Towers Islamabad",
      "Pak China Mall Islamabad",
      "Pakland Towers Islamabad",
      "One Constitution Avinue Islamabad",
      "Gulberg Heights Islamabad",
      "Diamond Mall & Residency Rawalpindi",
      "KRL Hospital Islamabad",
      "Kazani Heights Islamabad",
      "Bahria Town Head Office Rawalpindi",
      "Sukh Chayn Residence Islamabad",
      "Skypark One, Gulberg Islamabad",
      "PNS Hafeez Hospital Naval Headquarter Islamabad",
      "Terrace Apartment Park View Islamabad",
      "Serene Heights Gulberg Green Islamabad",
      "Premier Choice 68 High Street Bahria Town Rawalpindi",
      "Emporium Mall & Residency Islamabad",
      "Information Technology Park Islamabad",
      "5G Emporium Top City Islamabad",
      "360 the Residence Bara Kahu Islamabad",
      "Mosaic District Islamabad",
      "KFC Rawalpindi",
      "Army Public School DHA Phase-5 Islamabd",
      "Holy Family Government Hospital Rawalpindi",
      "Khaadi at Zeta Mall Islamabd",
      "Sapphire F-10 Islamabad",
      "Mian Group of Chakwal in Bahria Town Phase-8 Rawalpindi",
      "Mega Medical Complex Hospital Rawalpindi",
      "Life Style Residency Islamabad",
      "PIMS Hospital Islamabad Government of Punjab",
      "Majestic Mall Islamabad",
      "The Garden Residence Islamabad",
    ],
  },
  {
    name: "Lahore",
    projects: [
      "CMH Lahore Medical College",
      "Pakistan Air Force Base Lahore (PAF)",
      "King Edward Medical University Lahore",
      "University of Central Punjab, Lahore",
      "Omar Hospital Lahore",
      "Ndure Outlet Lahore",
      "Packages Mall Lahore",
      "Lahore High Court",
      "Downtown Mall Liberty Lahore",
      "Bioron Medics Lahore",
      "Lahore Medical & Dental College Hospital",
      "Indus Hospital Lahore",
      "Xinwa Mall Gulberg Lahore",
      "Askari Tower Lahore",
      "Punjab Group of Collegs Lahore",
      "Amana Mall Lahore",
      "Beacon House Lahore",
      "Zainab Tower Lahore",
      "Pefda Lahore",
      "MAP Hostel Lahore",
      "Indigo Height Lahore",
      "Ali Villa Behria Town Lahore",
      "Imtiaz Store Behria Town Lahore",
      "Kayseria Lahore",
      "Hangten Lahore",
      "Lake City Mall Lahore",
      "Stylo Shoes Lahore",
      "Duniya News Lahore",
      "University of Lahore",
      "Ripha University Lahore",
      "Care Hospital Lahore",
      "MYO Hoapital Lahore",
      "PAF Hospital Cantt Lahore",
      "Penta Square DHA Lahore",
      "Jinnah Hospital Lahore Government of Punjab",
      "Green Building Lahore Government of Punjab",
      "One Home Lahore",
      "Punjab Local Govt. Academy Lahore",
      "18 Green Defence Raya DHA Lahore",
      "Nawaz Shareef Cancer Hospital Lahore Government of Punjab",
      "Ramada Hotel Lahore",
    ],
  },
  {
    name: "Karachi",
    projects: [
      "Kashmir Pre-engineered Construction (PVT) Ltd (KAPEC) Various Projects",
      "Diamond Residency Karachi",
      "Ramada Hotel Karachi",
      "United Communication Karachi",
      "Mohammad Ali Jinnah University, Karachi",
      "Lucky One Mall Karachi",
      "Consulate General of China Karachi",
      "Engro Polymer Karachi",
      "National Foods Office P.i.d.c Karachi",
      "Square One Mall Karachi",
      "Indus Motors Karachi",
      "Honda Showroom Clifton Karachi",
      "Hoshang Pearl Karachi",
      "Dr. Ziauddin Hospital Karachi",
      "Civil Hospital Karachi",
      "Bahria Heights Bahria Town Karachi",
      "Paragon Towers Bahria Town Karachi",
      "Artistic Fabric and Garment Industries (private) Limited Karachi",
      "Bahria Town Karachi Commercial and Residential Various Projects",
      "DHA City Karachi Commercial and Residential Various Projects",
      "Emaar Crescent Bay Pearl Tower 1 & 2 Karachi",
      "Emaar Park Edge Karachi",
      "Imtiaz Mega Zamzam Clifton Karachi",
      "Brentwood Signature 27 Karachi",
      "Bahria Complex One Karachi",
      "The Court Heights Karachi",
      "Sawera Club Karachi",
      "Balad Tower-2 and 3 Karachi",
      "City Towers & Shopping Mall Karachi",
      "Faizan-e-mustafa Offices Karachi",
      "Indigo Tower Karachi",
      "Karachi Institute of Kidney Diseases",
      "Shamsi Hospital",
      "Mega Mall Karachi",
      "Memon Medical Institute Hospital",
      "Kasim Textile",
      "Kasim Garments",
      "Soorty Enterprises (GROUP)",
      "Denium Clothing",
      "Rajby Industries",
      "Saya Tex (GROUP)",
      "Master Motors",
      "Tri-pack Films Limited",
      "Bona Papa Baby Daipers",
      "Novatex Limited",
      "Relaible Paint",
      "Mehran Spice & Food Industries",
      "Pak-arab Refinery",
      "Pakistan Refinery Limited",
      "Hilal Food (PVT) Ltd",
      "Genix Pharma (PVT) Ltd",
      "Epoch Pharmaceuticals",
      "KIRAN Hospital",
      "Memon Medical Institude Hospital",
      "National Medical Centre (NMC)",
      "Bosch Pharmaceuticals (PVT) Ltd",
      "Hilton Pharma",
      "Scilife Pharma (PVT) Ltd",
      "Getz Pharma (private) Ltd",
      "Sanofi-aventis Pakistan Limited",
      "The Smart School",
      "Olympia Project",
      "Dynasty Project",
      "Metropolis Project",
      "Gawadar Sea Pack",
      "Abdul Razzak Associate (ARA)",
      "Shanzil Group",
      "Al Mansoor Builders",
      "Abaseen Construction Co. (PVT) Ltd",
      "Creek Vistas Apartment",
      "Star City Mall",
      "Skyline Tower Defence",
      "Machiyara Group",
      "Pakistan Air Force Museum",
      "P.A.F Korangi Creek",
      "Saifee Hospital",
    ],
  },
  {
    name: "Faisalabad",
    projects: [
      "City Cash & Carry Faisalabad",
      "Family Mart Faisalabad",
      "DCO Office Faisalabad",
      "J. Branches Faisalabad",
      "Lyallpur Galleria Faisalabad",
      "Bank of Punjab Faisalabad",
      "Aspire College Faisalabad",
      "Jinnah Poly Technic Institute Faisalabad",
      "Tauseef Enterprises (PVT) Ltd Faisalabad",
      "FBR Office Faisalabad",
      "Civil Hospital Faisalabad",
      "Allied Hospital Faisalabad",
      "PINUM Cancer Hospital Faisalabad",
      "Government General Hospital Samanabad Faisalabad",
      "Government College University Faisalabad",
      "Paradise Marquee Canal Road Faisalabad",
      "Proton Marquee Canal Road Faisalabad",
      "Victoria Marquee Canal Road Faisalabad",
      "Garison Marquee Canal Road Faisalabad",
      "Close Knit Fabric Garment Faisalabad",
      "Government Special Education Center Faisalabad",
      "Shifa National Hospital Faisalabad",
    ],
  },
];
